//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Resource.rc에서 사용되고 있습니다.
//
#define IDD_UPDATINGFORM                101
#define IDD_PUTTINGFORM                 103
#define IDD_DRAWINGFORM                 105
#define IDD_FINDINGFORM                 107
#define IDC_STATIC_BUSINESSCARD         1001
#define IDC_STATIC_PERSONAL             1002
#define IDC_STATIC_COMPANY              1003
#define IDC_BUTTON_PUT                  1004
#define IDC_BUTTON_FIND                 1005
#define IDC_BUTTON_DRAW                 1006
#define IDC_BUTTON_ARRANGE              1007
#define IDC_BUTTON_FIRST                1008
#define IDC_BUTTON_PREVIOUS             1009
#define IDC_BUTTON_NEXT                 1010
#define IDC_BUTTON_LAST                 1011
#define IDC_STATIC_PERSONAL_NAME_I      1012
#define IDC_STATIC_PERSONAL_POSITION_I  1013
#define IDC_STATIC_PERSONAL_TELEPHONENUMBER_I 1014
#define IDC_STATIC_PERSONAL_EMAILADDRESS_I 1015
#define IDC_STATIC_COMPANY_NAME_I       1016
#define IDC_STATIC_COMPANY_ADDRESS_I    1017
#define IDC_STATIC_COMPANY_TELEPHONENUMBER_I 1018
#define IDC_STATIC_COMPANY_FAXNUMBER_I  1019
#define IDC_STATIC_COMPANY_URL_I        1020
#define IDC_STATIC_PERSONAL_NAME        1021
#define IDC_STATIC_PERSONAL_POSITION    1022
#define IDC_STATIC_PERSONAL_TELEPHONENUMBER 1023
#define IDC_STATIC_PERSONAL_EMAILADDRESS 1024
#define IDC_STATIC_COMPANY_NAME         1025
#define IDC_STATIC_COMPANY_ADDRESS      1026
#define IDC_STATIC_COMPANY_TELEPHONENUMBER 1027
#define IDC_STATIC_COMPANY_FAXNUMBER    1028
#define IDC_STATIC_COMPANY_URL          1029
#define IDC_STATIC_COMPANY_TELEPHONEMUBER_I 1031
#define IDC_EDIT_PERSONAL_NAME          1032
#define IDC_COMBO_PERSONAL_POSITION     1034
#define IDC_EDIT_PERSONAL_TELEPHONENUMBER 1035
#define IDC_EDIT_PERSONAL_CELLPHONENUMBER 1035
#define IDC_EDIT_PERSONAL_EMAILADDRESS  1036
#define IDC_STATIC_PERSONAL_AT          1037
#define IDC_COMBO_PERSONAL_EMAILADDRESS 1038
#define IDC_EDIT_COMPANY_NAME           1040
#define IDC_EDIT_COMPANY_ADDRESS        1041
#define IDC_EDIT_COMPANY_TELEPHONENUMBER 1042
#define IDC_EDIT_COMPANY_FAXNUMBER      1043
#define IDC_EDIT_COMPANY_URL            1044
#define IDC_STATIC_CONDITION            1046
#define IDC_BUTTON_SELECT               1049
#define IDC_STATIC_PERSONAL_CONDITION_NAME_I 1050
#define IDC_TREE_INDEXBINDER            1055
#define IDC_STATIC_PERSONAL_CELLPHONENUMBER 1056

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
